### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}

#### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "newbie1",
  "password": "newbie123",
  "email": "newbie@security.com",
  "role": "USER"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "newbie1",
  "password": "newbie123"
}

### GET Public status
GET http://localhost:8080/api/public/status


### GET Profile
GET http://localhost:8080/api/user/profile
Authorization: Bearer {token}

### GET Profile (no token)
GET http://localhost:8080/api/user/profile

### GET User data
GET http://localhost:8080/api/user/data
Authorization: Bearer {token}

### GET User data  (no token)
GET http://localhost:8080/api/user/data

### GET User info
GET http://localhost:8080/api/user/2
Authorization: Bearer {token}

### GET User info (other user)
GET http://localhost:8080/api/user/4
Authorization: Bearer {token}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "manager",
  "password": "password"
}

### GET Manager Dashboard
GET http://localhost:8080/api/manager/dashboard
Authorization: Bearer {token}

### GET Manager Team
GET http://localhost:8080/api/manager/team
Authorization: Bearer {token}

### GET Manager Reports
POST http://localhost:8080/api/manager/reports
Authorization: Bearer {token}
Content-Type: application/json

{"data": "hello world"}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}

### GET Profile
GET http://localhost:8080/api/user/profile
Authorization: Bearer {token}

### Refresh Token
POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{token}"
}

### Logout
POST http://localhost:8080/api/auth/logout
Content-Type: application/json

{
  "refreshToken": "{token}"
}