app:
  jwt:
    secret: "mySecretKey12345678901234567890123456789012345678901234567890"
    access-token-expiration: 30000      # 30? (????)
    refresh-token-expiration: 180000    # 3?  (????)
    issuer: "com.example.app"

spring:
  datasource:
    url: jdbc:h2:~/session-test;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.sb02.practice.security: DEBUG
    org.springframework.security: DEBUG